### PR TITLE
Sort IDs list based on the sorts of the table

### LINKED ISSUE #8: [Bug]: Doesn't consider table sort when creating the list of Ids
## What happened? 

Hey, 
When I have a table that is either sorted by a column or has a default sort, the list of IDs is created without considering the new order of the resources, thus confusing users trying to figure out which record will be next.

### How to reproduce the bug

Add the traits: `JoseEspinal\RecordNavigation\Traits\HasRecordsList` and `JoseEspinal\RecordNavigation\Traits\HasRecordNavigation` to both ListResources and EditResource respectively of a resource that has a table that has either sortable columns or a [defaultSort](https://filamentphp.com/docs/3.x/tables/columns/getting-started#sorting-by-default).

Now the record navigation works in non expected way because its list doesn't match the tables list.

### Package Version

2.0.0

### PHP Version

8.2

### Laravel Version

11.9

### Which operating systems does with happen with?

macOS

### Notes

_No response_

### PR DESCRIPTION
**Pull request by UendelC**
closes #8

### CODE REVIEW

**Comment by dagalumin** [comment]
Hello @UendelC,
your solution doesn't work if the table is ordered by a relationship column. The `$query->orderBy($sort, $direction)` doesn't work if `$sort` is a relationship like `relationshipName.attribute`, it gives a `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relationshipName.attribute' in 'order clause'`.

Changing that line with this would instead work also for a relationships:
`$this->getTable()->getSortableVisibleColumn($sort)->applySort($query, $direction);`


Note: the rows returned by this query are internally reorderd by the record Id, after the chosen column ordering. This can be different from the row ordering shown on the table, since there the DB can return the records in any order.
This means that the ids written in the session by the HasRecordsListOrdered trait, can be in a different order respect to the records shown in the table, creating some confusion while navigating the records in Edit.

I still couldn't find a solution to overcome that: one idea could be to always give a fixed secondary ordering to the main table records by Id, so the records written in the session and the ones shown in the table would be in the same order; it doesn't seem there's any simple way to give a secondary ordering to a Filament Table, so that if you order by a column the records would be subsequently ordered also by Id: methods like defaultSort, modifyQueryUsing, getEloquentQuery, or a closure in sortable(), they all overwrite the column ordering chosen by the user.

File: src/Traits/HasRecordsList.php [hunk 1]
```diff
@@ -17,6 +17,13 @@ public function rendered($view, $html)
             );
         }
 
+        $direction = $this->tableSortDirection ?? $this->getTable()->getDefaultSortDirection() ?? 'asc';
+        $sort = $this->tableSortColumn ?? $this->getTable()->getDefaultSort($query, $direction);
+
+        if ($sort) {
+            $query->orderBy($sort, $direction);
```
Comment (dagalumin) [inline src/Traits/HasRecordsList.php:24]: better change `$query->orderBy($sort, $direction)` with:
`$this->getTable()->getSortableVisibleColumn($sort)->applySort($query, $direction);`
to work with relationship column ordering.

The normal orderBy doesn't work if the table is ordered by a relationship column: if $sort is a relationship like `relationshipName.attribute`, it gives a `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relationshipName.attribute' in 'order clause'`.

Note: the rows returned by the query are internally reorderd by the record Id, after the chosen column ordering. This can be different from the row ordering shown on the table, since there the DB can return the records in any order.
This means that the ids written in the session by the HasRecordsListOrdered trait, can be in a different order respect to the records shown in the table, creating some confusion while navigating the records in Edit.

I still couldn't find a solution to overcome that: one idea could be to always give a fixed secondary ordering to the main table records by Id, so the records written in the session and the ones shown in the table would be in the same order; it doesn't seem there's any simple way to give a secondary ordering to a Filament Table, so that if you order by a column the records would be subsequently ordered also by Id: methods like defaultSort, modifyQueryUsing, getEloquentQuery, or a closure in sortable(), they all overwrite the column ordering chosen by the user.

**Comment by mberneis** [comment]
+1 - Please merge/incorporate - I need this functionality as well.
